### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by wolfworld6** [happyharrycn/actionformer_release#1]
great work，could you provide the pretrained model？thx！

**Comment by happyharrycn** [comment]
I can look into this later week. You are encouraged to train these models. With a modern GPU, the training takes ~30 minutes on THUMOS, ~1 hour on  ActivityNet  and EPIC-Kitchens.

**Comment by wolfworld6** [comment]
> I can look into this later week. You are encouraged to train these models. With a modern GPU, the training takes ~30 minutes on THUMOS, ~1 hour on ActivityNet / EPIC-Kitchens.

yep,thx!
