### ISSUE TITLE
anet_1.3_i3d.tar.gz

### ISSUE THREAD

**Issue by dmmSJTU** [happyharrycn/actionformer_release#104]
Hello, could you send the anet_1.3_i3d.tar.gz to me? The download reaches more than 90%, it will be disconnected. My email is dmm2020@sjtu.edu.cn. Thank you very much.

**Comment by happyharrycn** [comment]
We provided multiple downloading links for ActivityNet features. If one of them does not work for you, try others. We won't be able to send those features via email.

**Comment by dmmSJTU** [comment]
Hello, there is only one download link about anet_1.3_i3d.tar.gz.

**Comment by tzzcl** [comment]
We have Google Drive, Box and BaiduYun Link for both features, please read README.md carefully.
