### ISSUE TITLE
May I ask why there is warn: "No predictions of label '16' were provdied".

### ISSUE THREAD

**Issue by ClancyAyres** [happyharrycn/actionformer_release#105]
<img width="556" alt="image" src="https://github.com/happyharrycn/actionformer_release/assets/56544641/d47ce1af-adf1-4174-a890-122b6ec2bf6e">

**Comment by shiyi-z** [comment]
i have the same problem, when i eval the thumos dataset, it work nomally. but when i  eval the anet, some warning occured to it.
![image](https://github.com/happyharrycn/actionformer_release/assets/79558156/1e79ad3d-8d34-4d78-8c41-b14f3bd9cf01)

**Comment by ClancyAyres** [comment]
My understanding is: the number of training is too small, and some categories have not yet appeared. If the parameters after multiple rounds of eval, this problem will disappear

**Comment by happyharrycn** [comment]
If you evaluate an early checkpoint of the model, you might see something like this, as the concepts of those categories are not learned. 

For ActivityNet, please make sure that the same config is used for training and evaluation. A similar error can occur if the external score is enabled during training yet disabled at inference time.

**Comment by happyharrycn** [comment]
Closed due to inactivity.
