### ISSUE TITLE
Missing video in THUMOS14 I3D features

### ISSUE THREAD

**Issue by Jaswar** [happyharrycn/actionformer_release#107]
Hi, thank you for this amazing contribution. I have downloaded the I3D features for the THUMOS'14 dataset using the [Google Drive](https://drive.google.com/file/d/1zt2eoldshf99vJMDuu8jqxda55dCyhZP/view) link. In your paper, it is mentioned there are 213 test videos and 200 validation videos. This checks out with the number of files in the `i3d_features` folder, as there are 413 files. However, the `thumos14.json` annotations file, seems to only contain 412 annotations for 212 test videos and 200 validation videos. The missing video seems to be `video_test_0001292`. The file for that video exists in the `i3d_features` folder.

Am I missing something or is the annotation for that file indeed missing? If it is missing, what was the reason for exclusion? 

Thank you for your help in advance.

**Comment by happyharrycn** [comment]
If I recall correctly, that missing video does not contain any annotated events, and is thus excluded. You can double check this using the official annotations of THUMOS'14 dataset.

**Comment by Jaswar** [comment]
Indeed, having checked the annotations from the original file, this video does not appear in any action class. Thank you for your help.

I have however, a follow up question. If I'm understanding the codebase correctly, wouldn't excluding this video from the annotations file also exclude it from testing (as I believe they are similarly excluded in ActivityNet #57)? If so, why exactly is that done? Wouldn't it also make sense to test on videos that contain no action?
