### ISSUE TITLE
Feature dimension 

### ISSUE THREAD

**Issue by DoublePan-Oh** [happyharrycn/actionformer_release#11]
For ActivityNet dataset, you use TSP model to get its feature. I want to konw how can you get the feature dimention [T,C]. As I know, the output feature dimention of TSP is [ feature size ].

**Comment by happyharrycn** [comment]
This is what we have described in the readme file. Let me know if the following description is not clear to you. 

_The features are extracted from the R(2+1)D-34 model pretrained with TSP on ActivityNet using clips of 16 frames at a frame rate of 15 fps and a stride of 16 frames (i.e., non-overlapping clips). This gives one feature vector per 16/15 ~= 1.067 seconds (of an input video)._

**Comment by DoublePan-Oh** [comment]
I try to extract features from https://github.com/HumamAlwassel/TSP/blob/master/extract_features/README.md, but I found the feature dimention is [512], It does not match the feature dimension[T,C], how can you get the T dimention?

**Comment by happyharrycn** [comment]
I can't reproduce the issue you mentioned here. The code repo of TSP will extract features of size T x C by default, where T is the number of clips in a video and C is the feature channel. You might want to double check if you followed their instructions closely (in particular the video encoding). If you have further questions regarding TSP features, please open an issue in their repo.

**Comment by happyharrycn** [comment]
Mark as resolved.
