### ISSUE TITLE
Difficulty in parallelizing MSAs on GPUs

### ISSUE THREAD

**Issue by Jaswar** [happyharrycn/actionformer_release#111]
Hi,

In your paper you mention that "It is known that self-attention is not easily parallelizable on GPUs" (_Window Size for Local Self-Attention_ in _Ablation Experiments_). I tried looking for works/sources that would mention this as an issue as well, but I couldn't find any. Could you maybe explain or provide sources for why self-attention is not easily parallelizable?

**Comment by happyharrycn** [comment]
The text here was intended to refer to the difficulty of efficient implementation of self-attention on GPUs, which is mostly memory IO bounded. See these papers for some discussion [link1](https://arxiv.org/abs/2205.14135) [link2](https://dl.acm.org/doi/10.1145/3458817.3476138).
