### ISSUE TITLE
Slowfast pre-trained model  on Epic-kitchen

### ISSUE THREAD

**Issue by EmreOzkose** [happyharrycn/actionformer_release#116]
Hi, thank you for sharing your great work. 

Is there any plan to share a slow-fast model which is finetuned on Epic-kitchen?

**Comment by happyharrycn** [comment]
You can find a SlowFast model finetuned on EPIC-Kitchens in [this repo](https://github.com/epic-kitchens/epic-kitchens-slowfast), which we used for feature extraction.

**Comment by EmreOzkose** [comment]
thank you!
