### ISSUE TITLE
problem about truncate_feats() function in data_utils.py

### ISSUE THREAD

**Issue by Charlestar** [happyharrycn/actionformer_release#117]
In data_utils.py line 78, there is
```python
left = torch.maximum(window[:, 0] - offset, data_dict['segments'][:, 0])
right = torch.minimum(window[:, 1] + offset, data_dict['segments'][:, 1])
```
I can't understand why we need to plus and minus offset here.
In my opinion, `data_dict['segments']` and `feats` has already aligned before, and in this function, there will no problem about offset, the window is generated initially with offset.
Maybe my understanding is wrong, please help me！

**Comment by tzzcl** [comment]
Please see the [FAQ.md](https://github.com/happyharrycn/actionformer_release/blob/main/FAQ.md) for questions about offsets.

**Comment by tzzcl** [comment]
Sorry for misunderstanding your questions, I think the problem is:

We want to truncate the feature sequence to perform data augmentation. Thus, we random choose the starting index with max_seq_len. Then, we need to complete the alignment again as you see in thumos14 dataloader.

**Comment by Charlestar** [comment]
I don't think this reason convinces me, max_seq_len is also considered after the alignment.
Maybe I'll give an example to understand better, let us consider a borderline case, the action is so long that exceeded (max_seq_len + 2 * offset), and the random st satisfied `st - offset > action start` and `ed = st + max_seq_len < action end`, if just specify `has_action=True`, then the function `truncate_feats()` will return a segment of length `max_seq_len + 2*offset`, I think this breaks the `max_seq_len` setting and may harm to later program.

**Comment by happyharrycn** [comment]
It is important to notice that a spot in the feature grid lies in the center of a short time span (i.e., local window).  When truncating the feature and resetting the time stamps, we will need to identify the left border of the starting feature spot, and the right border of the ending feature spot. That is what implemented in the code here and we have verified that this is the right way of doing so.
