### ISSUE TITLE
Obtaining short segments

### ISSUE THREAD

**Issue by EmreOzkose** [happyharrycn/actionformer_release#118]
Hi, thanks for sharing great work. 

I tried to segment YouCook2 training videos and observed that actionformer gives much shorter segments. Do you have a clue about that? I tried this because I observed the same issue when I tested random YouTube videos.

**Comment by happyharrycn** [comment]
Detecting longer segment will require modifying the number of pyramid levels and tweaking the regression range on each level. One will need more levels and larger regression range in general.

**Comment by EmreOzkose** [comment]
The model which is trained on epic Kitchen produces short segments. I think this is because of the distribution of training data durations. On the other hand, activity-net produces longer segments.

**Comment by happyharrycn** [comment]
It looks like this is now resolved. I am marking this issue as closed. Feel free to re-open if needed.
