### ISSUE TITLE
Some Confusion about annotation

### ISSUE THREAD

**Issue by ddz16** [happyharrycn/actionformer_release#119]
In Thumos14 dataset, there are some confusing annotations. Two action instances with the same action label have temporal overlap. In that case, why not use a single action instance for annotation? For examples, in the "video_validation_0000983," there are two action instances as follows:

               ......
               {
                    "label": "VolleyballSpiking",
                    "segment": [
                        96.1,
                        97.4
                    ],
                    "segment(frames)": [
                        2883,
                        2922
                    ],
                    "label_id": 19
                },
                {
                    "label": "VolleyballSpiking",
                    "segment": [
                        96.9,
                        97.7
                    ],
                    "segment(frames)": [
                        2907,
                        2931
                    ],
                    "label_id": 19
                },
                ......

Why not use a single action instance for annotation, just like:

                {
                    "label": "VolleyballSpiking",
                    "segment": [
                        96.1,
                        97.7
                    ],
                },

**Comment by ddz16** [comment]
I have checked all the videos, and this situation is rare, only appearing in a few videos.

**Comment by tzzcl** [comment]
Closed due to inactivity.
