### ISSUE TITLE
Regarding the category settings in my own dataset

### ISSUE THREAD

**Issue by neauniko** [happyharrycn/actionformer_release#120]
Thanks for your work and detailed code!
If I only marked one behavior, how do I set it up?
I've tried differentiating between foreground and background, i.e. setting num_class=2, but it didn't have the desired effect.

**Comment by tzzcl** [comment]
You can just set the num_class as 1 (as the settings on ActivityNet).

**Comment by tzzcl** [comment]
Closed due to inactivity.
