### ISSUE TITLE
Regarding NMS

### ISSUE THREAD

**Issue by Moadab-AI** [happyharrycn/actionformer_release#121]
Hi,

Just wondering is there any particular reason you are not using torchvision's built-in nms (https://pytorch.org/vision/main/generated/torchvision.ops.nms.html#torchvision.ops.nms) simply by passing a (onset, 0, offset, 1) as bbox coordinates instead of all this cpp implementation?

**Comment by tzzcl** [comment]
You can choose torchvision's nms for your convenience.

**Comment by happyharrycn** [comment]
NMS in torchvision is designed for 2D cases and does not support soft NMS. That is why we implemented a cpp version.
