### ISSUE TITLE
特征提取

### ISSUE THREAD

**Issue by miaolin968** [happyharrycn/actionformer_release#126]
你好！在您指出的I3D特征提取网络中将视频帧率转化为25，但是Thumos14数据集的原始帧率是30，请问您使用的特征对视频帧率进行了转化吗？这对之后的网络性能是否有影响呢？

**Comment by happyharrycn** [comment]
Mark as closed.

**Comment by miaolin968** [comment]
感谢回复！同时请问您的模型使用tensorboard版本是多少？

**Comment by tzzcl** [comment]
We don't limit the tensorboard version and I think popular tensorboard version should be OK.
