### ISSUE TITLE
About nms config

### ISSUE THREAD

**Issue by ring-zl** [happyharrycn/actionformer_release#127]
"Why is the confidence threshold for NMS set quite low in the experiment, resulting in a significantly high number of prediction outputs? Is this practically feasible? Moreover, why does appropriately increasing the NMS confidence threshold (for instance, to 0.1 or 0.3) lead to a noticeable decrease in mAP?"

**Comment by tzzcl** [comment]
low confidence threshold aims to improve the recall for temporal action detection, this trick is common in object detection and temporal action detection.

**Comment by ring-zl** [comment]
thank you. What surprises me is that this rather extreme approach leads to a significant increase in the number of False Positives , but ultimately results in a noticeable improvement in the mAP metric。

**Comment by happyharrycn** [comment]
To clarify, we are using soft NMS, which does not impose a threshold and keeps all detection output. If you are looking at _iou_threshold_, this is ignored for soft NMS.
