### ISSUE TITLE
What does it mean that the len of the epic_kitchens data is 3?

### ISSUE THREAD

**Issue by SanMumumu** [happyharrycn/actionformer_release#129]
c = np.load("./epic_kitchens/features/P04_33.npz")
len(c)
3
How do I understand this .npz file?

-----------------------------------------------

And how did you acquire the 'epic_kitchens_100_noun.json' and 'epic_kitchens_100_verb.json' files

**Comment by happyharrycn** [comment]
The npz file stores a dictionary with 3 keys: "feats", "n_probs" and "v_probs". The "feats" key stores the clip-level features from the SlowFast network (before the last classifier), and "n_probs" and "v_probs" records the classification results (probability) for verbs and nouns. "n_probs" and "v_probs" were not considered in our model. 

The json files were converted from the official annotations (CSV format).

**Comment by happyharrycn** [comment]
Closed due to inactivity.
