### ISSUE TITLE
About visualization

### ISSUE THREAD

**Issue by nqxjzm** [happyharrycn/actionformer_release#13]
Great work! Sorry to bother you.
I want to ask  how to get your visualization results on  the regression of the localization. 
I am very grateful if you can get it and give me an answer!

**Comment by tzzcl** [comment]
Hi, I can not fully understand your problem.

For the regression, We first generate points according to FPN features, than we add regression results to each point to get the final segments.

For point generation part, you may want to refer to [PointGenerator](https://github.com/happyharrycn/actionformer_release/blob/main/libs/modeling/loc_generators.py#L28) for details.

For the inference process, you may want to refer to the [inference_single_video](https://github.com/happyharrycn/actionformer_release/blob/bc22e776e857ad46cb9f5f62deead1582eb08494/libs/modeling/meta_archs.py#L634) function for details.

**Comment by nqxjzm** [comment]
Thanks for your reply very much!
I'm sorry for not illustrate the question clearly, I just want to know  how  to get the predicted onset and offset visualization like it on the end of your paper.

**Comment by tzzcl** [comment]
I think you may need to refer to [inference_single_video](https://github.com/happyharrycn/actionformer_release/blob/bc22e776e857ad46cb9f5f62deead1582eb08494/libs/modeling/meta_archs.py#L634) function for details.

In the function, the final predicted segments are generated by [L677-L678](https://github.com/happyharrycn/actionformer_release/blob/bc22e776e857ad46cb9f5f62deead1582eb08494/libs/modeling/meta_archs.py#L677-L678).  pts[:,0] is the point coordinate and pts[:,3] is the point stride, offsets[:,0] and offsets[:,1] are the predicted onsets and offsets.

**Comment by nqxjzm** [comment]
Thanks for your detailed answer! I get it!

**Comment by 0829MingHu** [comment]
@nqxjzm I think I encountered some problems when reproducing the visualization, can I share with you? My email: ming.hu@monash.edu, or please leave your email and I will contact you，thanks a lot!
