### ISSUE TITLE
how to view result?

### ISSUE THREAD

**Issue by ruiming46zrm** [happyharrycn/actionformer_release#131]
do you have any demo?  to view the result of several videos

**Comment by happyharrycn** [comment]
We do not include the visualization code as part of this repo, though it should be straightforward to code up one.

**Comment by happyharrycn** [comment]
Closed due to inactivity.

**Comment by Gi-gigi** [comment]
> Closed due to inactivity.

@happyharrycn  Can you provide visual code for learning now? Thank you so much.
