### ISSUE TITLE
Error when trying my own dataset

### ISSUE THREAD

**Issue by darthandvader** [happyharrycn/actionformer_release#132]
File "/actionformer_release/libs/modeling/meta_archs.py", line 409, in preprocessing
    pad_feat[..., :feat.shape[-1]].copy_(feat)
RuntimeError: The size of tensor a (3) must match the size of tensor b (360) at non-singleton dimension 2

Hi, I formulate my dataset in the format of thumos and used thumos config to train, but encountered this error, wondering how to address that.

**Comment by happyharrycn** [comment]
This looks like the features stored in the npy files were not formatted properly. The THUMOS dataloader expects video features of size T x C in each npy file, with T as the number of time steps and C as the number of feature channels. You might want to double check this part.

**Comment by happyharrycn** [comment]
Closed due to inactivity.
