### ISSUE TITLE
关于提供的EPIC-KITCHENS-100数据集中label的字典问题

### ISSUE THREAD

**Issue by XD-mu** [happyharrycn/actionformer_release#135]
您好作者，对你的工作非常感兴趣，我在复现您的EPIC-KITCHENS-100数据集的时候发现它的annotion中label和label_id都是一样的：{"label": "41", "label_id": 41, "segment": [417.36, 418.11]}
我现在想要知道每个数字对应的verb和none这两个文件都是哪些类别，请问您那里有备份嘛，方便提供一下吗？

非常感谢！

**Comment by tzzcl** [comment]
for epic kitchen labels, we directly convert the original epic-kitchens verb and noun labels into numerical labels by lexicographic order. You can directly sort the verb and noun labels.

**Comment by happyharrycn** [comment]
I am closing this issue for now. Let me know if you have further questions.

**Comment by XD-mu** [comment]
no, thanks!
