### ISSUE TITLE
A question about SimOTA relative code

### ISSUE THREAD

**Issue by ayiyayi** [happyharrycn/actionformer_release#136]
Hi! 
Thanks for your excellent work. In 2023 EgoMQ Challenge, you adopt SimOTA for dynamic label assignment strategy. However, I seem to have trouble locating the relevant code. Could you kindly direct me to the relevant code?
Thank you very much!

**Comment by tzzcl** [comment]
We didn't add the related SimOTA code in this repo, but you can refer to the [TemporalMaxer's Implementation](https://github.com/TuanTNG/TemporalMaxer/blob/master/libs/modeling/simota_assigner.py) for the detailed code.

**Comment by ayiyayi** [comment]
Thank you!
