### ISSUE TITLE
K-way Binary Classification vs. Multi-class Classification

### ISSUE THREAD

**Issue by WenliangGuo** [happyharrycn/actionformer_release#139]
Thanks for your wonderful work! My question is that why you choose to treat a K-way classification as K binary classification for action label prediction. Is this an experimental result that binary focal loss outperforms CE loss, or there are some other motivation behind it?

**Comment by tzzcl** [comment]
With the label assignment strategy in ActionFormer, positive samples will be much smaller than positive samples, thus we choose K-way binary classification along with focal loss.

**Comment by WenliangGuo** [comment]
Thanks for your answer!
