### ISSUE TITLE
数据后处理

### ISSUE THREAD

**Issue by DD-BONED** [happyharrycn/actionformer_release#14]
你好怎么使用postprocessing对结果预测

**Comment by tzzcl** [comment]
你好，很抱歉我不是非常明白你的问题。

关于后处理与可视化相关的问题，你可以参考[Issue 13](https://github.com/happyharrycn/actionformer_release/issues/13)里面的回复。

**Comment by happyharrycn** [comment]
Let me know if there is any further questions. Otherwise, I will mark the issue as resolved.

**Comment by DD-BONED** [comment]
你好文章中讲fpn有效请问想看看没有fpn的效果应该怎样设置参数成功运行

**Comment by tzzcl** [comment]
你好，在文章中，我们说明了FPN并没有作用。

如果你想尝试FPN的话，可以将config里面的fpn_type从identity变为fpn。如[thumos_i3d.yaml](https://github.com/happyharrycn/actionformer_release/blob/main/configs/thumos_i3d.yaml#L19)里的这行。

**Comment by DD-BONED** [comment]
我的意思文章中backbone的结构是225如果想改成221的话应该怎么设置

**Comment by tzzcl** [comment]
在[config.py](https://github.com/happyharrycn/actionformer_release/blob/main/libs/core/config.py#L47)里面，存放着一些默认参数，如果你想修改结构，可以在config里面添加对应的字段，并且修改regression_range.

**Comment by DD-BONED** [comment]
thanks,your help.how to use your code to get Figure A.3. More visualization of our outputs.

**Comment by tzzcl** [comment]
关于后处理与可视化相关的问题，你可以参考[Issue 13](https://github.com/happyharrycn/actionformer_release/issues/13)里面的回复。从pts和offsets得到点的坐标和对应的offset，然后进行可视化

**Comment by happyharrycn** [comment]
Let me know if this issue was addressed.

**Comment by happyharrycn** [comment]
Mark as resolved.

**Comment by DD-BONED** [comment]
你好输出result得到了{'video_id': 'video_test_0000737', 'segments': tensor([[118.3025, 137.3431],
        [ 32.9606,  43.5419]，请问segments指的的真实视频里面的秒吗，比如32.9606s,  43.5419s时video_test_0000737发生了动作？

**Comment by DD-BONED** [comment]
你好输出result得到了{'video_id': 'video_test_0000737', 'segments': tensor([[118.3025, 137.3431],
        [ 32.9606,  43.5419]，请问segments指的的真实视频里面的秒吗，比如32.9606s,  43.5419s时video_test_0000737发生了动作？

**Comment by tzzcl** [comment]
是的

**Comment by DD-BONED** [comment]
感谢师兄的回复，时隔一年我的工作也即将发表，非常感谢您的帮助




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "happyharrycn/actionformer_release"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月8日(星期五) 下午4:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [happyharrycn/actionformer_release] 数据后处理 (Issue #14)





 
在config.py里面，存放着一些默认参数，如果你想修改结构，可以在config里面添加对应的字段，并且修改regression_range.
