### ISSUE TITLE
where logs

### ISSUE THREAD

**Issue by JYW333** [happyharrycn/actionformer_release#140]
Hello, in your article, you mentioned: "Train our ActionFormer with I3D features on THUMOS14. This will create an experiment folder under ./ckpt that stores training config, logs, and checkpoints." However, when I was training, there were no log files, and thus I couldn't use TensorBoard. What could be the issue?

**Comment by happyharrycn** [comment]
If the training is successfully started, logs will saved under ./ckpt, unless the output_folder was modified in the config file. What is your terminal output during training?

**Comment by JYW333** [comment]
![terminal output](https://github.com/user-attachments/assets/5f20ff7e-44af-4346-a30f-fd04fe834498)
![file](https://github.com/user-attachments/assets/16bff433-09e2-425a-95c4-2062fecfc056)
Hello, thank you for your response. The first image is the output from my terminal, and the second image shows the contents of the thumos_i3d_reproduce folder under ./ckpt after my training. However, I have downloaded your pre-trained files, and under this thumos_i3d_reproduce folder, there  be a logs folder included. But when I train myself, there isn't one. Could you please tell me where the problems?

**Comment by happyharrycn** [comment]
It looks like you are using TriDet repo, which removed the TensorBoard logging functionality. While TriDet is also based on our repo, we will only address questions related to this repo.
