### ISSUE TITLE
Clarification on mAP Score Variations Across Machines/GPUs

### ISSUE THREAD

**Issue by krkrkrrk** [happyharrycn/actionformer_release#142]
Hello.

In your paper, you mention that there are minor variations in the average mAP scores across machines/GPUs and computing environments. Could you provide more details on the specific causes of these variations? For example, are they related to hardware differences, numerical precision, or software implementation inconsistencies? Additionally, are there any reliable sources or references that discuss such variations in detail?

**Comment by tzzcl** [comment]
Hello, I think there may exist following causes:

1. Hardware differences: for different types of GPUs like A100/H100, even with same operation (conv, etc), the results will not be the same. 
2. Software differences. Different PyTorch/CUDA/CUDNN version may also provides different results (but in a reasonable variation).

For more references, you can refer to [reproducibility](https://pytorch.org/docs/stable/notes/randomness.html#reproducibility) section in PyTorch.

**Comment by krkrkrrk** [comment]
Thank you for your reply.
