### ISSUE TITLE
How can I get the predicted onset and prediected offset

### ISSUE THREAD

**Issue by yalimasinei** [happyharrycn/actionformer_release#18]
I want to get the predicted result and compare this with the true result ,can anyone give me  a guide

**Comment by tzzcl** [comment]
Please refer to [Issue 13](https://github.com/happyharrycn/actionformer_release/issues/13) for details.

**Comment by happyharrycn** [comment]
Let me know if there is any further questions. Otherwise, I will mark the issue as resolved.

**Comment by yalimasinei** [comment]
> Let me know if there is any further questions. Otherwise, I will mark the issue as resolved.
another question .I apply your model on UCF101(thumos14) but  it works badly with the I3d codes from this [link](https://github.com/GowthamGottimukkala/I3D_Feature_Extraction_resnet).So  could you please give me your I3d codes(for extracting features) and the unprocessed datasets（video not features） ？

**Comment by tzzcl** [comment]
Hi, for THUMOS14 dataset, we use the feature provided by [CMCS](https://github.com/Finspire13/CMCS-Temporal-Action-Localization). The CMCS uses [pytorch-i3d-feature-extraction](https://github.com/Finspire13/pytorch-i3d-feature-extraction) to extract the features. I think the link you mentioned is a I3D ResNet model. and you should pay attention to the feature stride part. For the unprocessed video part, you can refer to the official THUMOS14 website.

> > Let me know if there is any further questions. Otherwise, I will mark the issue as resolved.
> > another question. I apply your model on UCF101(thumos14) but  it works badly with the I3d codes from this [link](https://github.com/GowthamGottimukkala/I3D_Feature_Extraction_resnet). So  could you please give me your I3d codes(for extracting features)  and the unprocessed datasets（video, not features） ？

**Comment by happyharrycn** [comment]
When using a different version of I3D, the feature dimension / stride / size of local window need to be adjusted accordingly in the config file.

The original issue is about the prediction outputs. If you have questions regarding feature extraction, please open a new issue.
