### ISSUE TITLE
External Classifier scores are larger than 1

### ISSUE THREAD

**Issue by klauscc** [happyharrycn/actionformer_release#19]
Thanks for your great work!
When I check the scores of the external classifier on THUMOS dataset, I found the max scores and sum of all the scores for one video are larger than 1.
For example:

```
>>> import pickle as pkl
>>> scores= pkl.load(open('thumos14_cls_scores.pkl','rb'))
>>> k="video_test_0000004"; scores[k];sum(scores[k])
array([0.02432016, 0.03033004, 0.00686024, 0.00082171, 0.00296591,
       0.40734518, 0.3418732 , 0.11635409, 0.21866749, 0.00644728,
       0.0069871 , 0.03885338, 0.073525  , 0.01213155, 0.01179111,
       0.0214216 , 0.10836662, 0.09010944, 0.01251512, 0.09871857],
      dtype=float32)
1.6304047908633947
>>> k="video_test_0000786"
>>> k="video_test_0000786";scores[k];sum(scores[k])
array([1.4641240e-01, 3.0841224e-04, 5.1868934e-05, 1.9699870e-05,
       1.0326537e-05, 1.2187198e+00, 6.0507798e-01, 1.5942456e-05,
       1.3059583e-03, 1.2300874e-04, 4.0310311e-05, 2.0225532e-03,
       2.5760273e-03, 4.8151556e-05, 1.1477998e-04, 6.2134140e-04,
       3.6271741e-03, 8.6841742e-03, 3.3115208e-05, 8.4242632e-04],
      dtype=float32)
1.9906554949593556
```

These scores seems already after softmax. It would be great if you can explain how you scale them. Thanks a lot!

**Comment by tzzcl** [comment]
As we shown in the paper, the external score is generated by [UntrimmedNet](https://arxiv.org/pdf/1703.03329.pdf), it is not a simple softmax classifier, thus the sum of prob may not be 1. 

For your second question, we do not directly perform scaling to the external classification scores. As shown in [postprocessing.py](https://github.com/happyharrycn/actionformer_release/blob/main/libs/utils/postprocessing.py#L124) only pick the top 2 predictions, and using the square root of (predicted score * cls score) in the paper to form the final scores. We follow the suggestions in [Appendix E of P-GCN](https://arxiv.org/pdf/1909.03252.pdf). You may want to refer to the P-GCN paper for details.

**Comment by klauscc** [comment]
Thanks a lot for your explanation!

**Comment by happyharrycn** [comment]
Let me know if this issue is now addressed.

**Comment by happyharrycn** [comment]
Mark as resolved.
