### ISSUE TITLE
where is the undeterministic implementation？

### ISSUE THREAD

**Issue by juipengchang** [happyharrycn/actionformer_release#20]
If run the code directly, I will get the following error:

RuntimeError: index_add_cuda_ does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True)'. You can turn off determinism just for this operation if that's acceptable for your application. You can also file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation.

**Comment by tzzcl** [comment]
You may directly change the includ_cuda Flag to false in [fix_random_seed](https://github.com/happyharrycn/actionformer_release/blob/main/train.py#L54).

**Comment by happyharrycn** [comment]
The error is likely produced by either an older version of PyTorch or an old architecture of the GPU. Setting include_cuda to _False_ in train.py will switch to non-deterministic routines on the GPU.

**Comment by juipengchang** [comment]
> The error is likely produced by either an older version of PyTorch or an old architecture of the GPU. Setting include_cuda to _False_ in train.py will switch to non-deterministic routines on the GPU.

It can solve the problem but loss the reproducibility at the same time. I used PyTorch 1.8.1 and Nvidia 3090

**Comment by tzzcl** [comment]
We recommend to use the PyTorch version with 1.10+. In PyTorch 1.10+, it solves the reproducibility issue. You may want to switch to PyTorch 1.10+ and have another retry.

**Comment by juipengchang** [comment]
> We recommend to use the PyTorch version with 1.10+. In PyTorch 1.10+, it solves the reproducibility issue. You may want to switch to PyTorch 1.10+ and have another retry.

OK, thank you. I will have a try.
