### ISSUE TITLE
About window size

### ISSUE THREAD

**Issue by NooneOnlyOne** [happyharrycn/actionformer_release#23]
We found that you tested different window sizes for local self-attention, and I want to know when the window is Full, what the n_mha_win_size should be set to

**Comment by tzzcl** [comment]
For example, you should set `n_mha_win_size`  to -1 in the config file.

The code are [from here](https://github.com/happyharrycn/actionformer_release/blob/main/libs/modeling/blocks.py).

If mha_win_size >1, local attention is used, otherwise global attention is used.

**Comment by NooneOnlyOne** [comment]
Thank you for the reply
