### ISSUE TITLE
About compilation of NMS

### ISSUE THREAD

**Issue by fuchenye123** [happyharrycn/actionformer_release#27]
When conducting compilation of NMS, an error occurs: "RuntimeError: Error compiling objects for extension",
I use:

Python 3.6.10
CUDA 11.3
Pytorch 1.10

Can you help me?
Thanks.

**Comment by tzzcl** [comment]
Could you show me the detailed error log?

I've tried that with 
CUDA 11.1
PyTorch 1.10/PyTorch 1.11
Python 3.8/Python3.7

It both works fine.

**Comment by fuchenye123** [comment]
Thanks for your reply!
I tried that with CUDA 11.3 PyTorch 1.10 Python 3.8, but it still failed
The error log has been submitted to the appendix





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "happyharrycn/actionformer_release"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月13日(星期五) 下午3:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [happyharrycn/actionformer_release] About compilation of NMS (Issue #27)





 
Could you show me the detailed error log?
 
I've tried that with
 CUDA 11.1
 PyTorch 1.10/PyTorch 1.11
 Python 3.8/Python3.7
 
It both works fine.

**Comment by fuchenye123** [comment]
> Could you show me the detailed error log?
> 
> I've tried that with CUDA 11.1 PyTorch 1.10/PyTorch 1.11 Python 3.8/Python3.7
> 
> It both works fine.

Thanks for your reply!
I tried that with CUDA 11.3 PyTorch 1.10 Python 3.8, but it still failed
The error log has been submitted to the appendix

**Comment by tzzcl** [comment]
I don't see the appendix file here.

A possible reason is that you may use the old gcc version (gcc <5), old gcc version can results in compile problems, you may want to switch to a higher gcc version (gcc 5 or gcc 7).

**Comment by fuchenye123** [comment]
The appendix is sent to your e-mail.
I am trying to switch to a higher gcc. Anyway, thanks for your suggestion

**Comment by tzzcl** [comment]
I don't receive your appendix here, you may directly send me an email with your log file.

**Comment by tzzcl** [comment]
Replied by external email. The problem is caused by different platform (Windows + Visual Studio).
