### ISSUE TITLE
About training on my own dataset

### ISSUE THREAD

**Issue by Yaosui12138** [happyharrycn/actionformer_release#28]
Thanks for your works first.And I'm trying to train the model on my own dataset, and found that there's a file named thumos14_cls_scores.pkl under thmos dataset.How can I generate the pkl file on my own dataset?

**Comment by happyharrycn** [comment]
This is the external classification score for THUMOS14 and is not needed for custom dataset. You can disable score fusion in the configuration file.

**Comment by Yaosui12138** [comment]
> 

Thanks for your reply!

**Comment by happyharrycn** [comment]
Mark as resolved.
