### ISSUE TITLE
About Visualization

### ISSUE THREAD

**Issue by xuan301** [happyharrycn/actionformer_release#30]
Hello, this is a very good job! If I want to use DETAD for visualization (FN, sensitivity analysis, etc.) as in your paper, can you provide the code to generate the json file of the results of your model？

**Comment by tzzcl** [comment]
Hi, Thank you for your interest in our project. We may not provide the convert code soon, but I can give you some instructions.

DETAD uses a standard evaluation process with GT json (they provided that in their repo) and predicted json, you only need to transfer the output to a valid json format.

With THUMOS14 dataset as an example, you first need to get the prediction output, you can use the `saveonly` args to get an output pickle file. The only thing is that you need to transfer the target pickle file to the specific json format. I think you only need to convert the class name.

**Comment by happyharrycn** [comment]
Mark as resolved.

**Comment by SimoLoca** [comment]
Hi, what should I do to use DETAD on EPIC results instead?

**Comment by tzzcl** [comment]
For EPIC datasets, you need to follow instructions in DETAD to create the groundtruth annotations file with extra annotations (like Context Size, Context Distance) as in the DETAD paper. Then you need to follow the previous answer to get the prediction json file and use DETAD to compute the figure.
