### ISSUE TITLE
About environment

### ISSUE THREAD

**Issue by NooneOnlyOne** [happyharrycn/actionformer_release#31]
Could you tell me the environment in which the code runs, such as the version of `pytorch` and `cuda`. Because I found that after you modified some code, running your code on the original environment is an error.
![image](https://user-images.githubusercontent.com/80327317/169195210-15de491e-4e5a-424b-bb3f-d6bb78874d0f.png)

**Comment by tzzcl** [comment]
Hi, In PyTorch 1.11, the torch API for deterministic algorithms has changed:

The original version:
`torch.use_deterministic_algorithms(mode)`

The new version:

`
torch.use_deterministic_algorithms(mode, *, warn_only=False)
`

You may upgrade the PyTorch version to 1.11.0 or use the old API.

**Comment by happyharrycn** [comment]
Good catch. We have moved to PyTorch 1.11. I've updated the INSTALL.md.

**Comment by happyharrycn** [comment]
Mark as resolved.
