### ISSUE TITLE
About the denominator of classification loss

### ISSUE THREAD

**Issue by sming256** [happyharrycn/actionformer_release#32]
Thanks for your great work! I would like to ask a question about the denominator of classification loss. 

As shown in Eq.7 in the paper, the classification loss (using sigmoid focal loss) is divided by the length of the valid input sequence. However, I found in your implementation, that the classification loss is divided by the number of positive samples, which is the same as regression loss. Can you explain the reason? Thanks. 

https://github.com/happyharrycn/actionformer_release/blob/c893d8ad0793d46ab8f9db5b7edc680b7c2e6a65/libs/modeling/meta_archs.py#L571

**Comment by happyharrycn** [comment]
Good catch! The denominator of the classification loss (Eq. 7 of our tech report) should be the number of positive samples. We will update the tech report soon. 

In practice, _self.loss_normalizer_ saves a moving average of the number of positive samples. The classification loss is summed over all samples, where the regression loss is summed over positive samples. Both are divided by  _self.loss_normalizer_  and are then added up.

**Comment by sming256** [comment]
Thanks for the reply! The moving average normalizer is a really good trick for stabilizing small batch training! 

I still want to have a further discussion about the classification loss. I guess it _should_ be divided by the number of all samples, just like in the original focal loss, instead of only positive samples. However, I also find that if in this way (divided by a moving average of the number of all samples), the classification loss value would be small and the final detection result is poor. 

So I wonder do you have any specific motivation for choosing such implementation, or just because it is a good weight for balancing the regression loss and classification loss. Please correct me if I am wrong. Thanks!

**Comment by happyharrycn** [comment]
Nice to have this discussion. The modern version of the focal loss (RetinaNet) uses a similar implementation, where both the classification loss (focal) and the regression loss (smoothed L1) are divided by the moving average of number of positive samples. See the code [here](https://github.com/facebookresearch/detectron2/blob/be67214add717fbdd0157521b2e63ea025164284/detectron2/modeling/meta_arch/retinanet.py#L207) in Detectron2. I think the choice here is mostly empirical.

**Comment by sming256** [comment]
Good to know that! Now it is clear.

Have a nice day!
