### ISSUE TITLE
About THUMOS14 in this repo

### ISSUE THREAD

**Issue by juipengchang** [happyharrycn/actionformer_release#33]
I have seen many different types of THUMOS14 in temporal action localization such as .json and .csv. Now I am making a new data set for temporal action localization, could you tell me if there any other method using the same type of data as yours? Thinks!

**Comment by happyharrycn** [comment]
To build on Chenlin's answer, we store video features in _npz_ (numpy arrays) and video annotations in json format. Our json file follows the annotation format of ActivityNet-1.3. To adapt our features, you can write a dataloader to parse the json file and load the features, similar to our dataloader in this repo.

**Comment by happyharrycn** [comment]
Let me know if this issue is still open. Otherwise, I will mark it as resolved.

**Comment by juipengchang** [comment]
Not yet. Think you for reply!

**Comment by tzzcl** [comment]
Can you illustrate more about your questions?

**Comment by juipengchang** [comment]
> Can you illustrate more about your questions?

I am trying to test many TAL models with my own data set. I have made my data set's label as your THUMOS14 label format and run your model successfully. However, other TAL models(such as [CMCS](https://github.com/Finspire13/CMCS-Temporal-Action-Localization)) have other input format and label format(such as [this](https://github.com/Finspire13/CMCS-Temporal-Action-Localization/blob/master/labels/thumos14-val-meta.mat)). I don't know how to generate these files of my data set, so I tried to find some methods which can run with your THUMOS14 labels directly. Now I now that you use ActivityNet format, so I am trying to find some methods which can used on ActivityNet.

**Comment by happyharrycn** [comment]
The json file following ActivityNet format simply records the action annotations in the videos. You can write some Python code to convert another format into the json format and vice versa. Or you can re-write the dataloader to allow our code to interface with another format.

**Comment by happyharrycn** [comment]
I am closing this issue as the discussion seems irrelevant to the current repo. Send us an email if an offline discussion is needed.
