### ISSUE TITLE
About performence 

### ISSUE THREAD

**Issue by nqxjzm** [happyharrycn/actionformer_release#37]
Great work！
I would like to know what specific changes you have made to make thumos14 perform better than before

**Comment by tzzcl** [comment]
In Table 3, we presented an detailed ablation on model design. Table 3 shows how we can reach 62.6% mAP on THUMOS14, compared to other methods. Moreover, we have around 67 mAP now.

**Comment by nqxjzm** [comment]
Because I can't reproduce your latest results

**Comment by tzzcl** [comment]
For the latest results, you may want to refer to the README and [this commit](https://github.com/happyharrycn/actionformer_release/commit/4e3a02b7aa0c7805e81a20bc1b6803e1baf72d71) for details.

**Comment by nqxjzm** [comment]
Thanks for your detailed reply！I use your current code,but I just get 65mAP at tiou=0.5  on thumos14 as follows
|tIoU = 0.30: mAP = 75.47 (%)
|tIoU = 0.40: mAP = 72.61 (%)
|tIoU = 0.50: mAP = 64.98 (%)
|tIoU = 0.60: mAP = 55.22 (%)
|tIoU = 0.70: mAP = 41.51 (%)
Avearge mAP: 61.96 (%)
All done! Total time: 39.79 sec

Process finished with exit code 0

**Comment by tzzcl** [comment]
The performance is similar to what we reported before in the report (65.6 vs 65.0 mAP with tIoU 0.5) and (62.6 vs 62.0 average mAP). I've run several times with the latest code on THUMOS14, the mean mAP is close to 66.0 mAP. Please make sure your code is at the latest commit ([5d8df9f](https://github.com/happyharrycn/actionformer_release/commit/5d8df9f89f95bbb2521d4d84188840591e29e8b4) and you use our features.

**Comment by happyharrycn** [comment]
I second to Chenlin's comment. By a quick look at your numbers, I think you are either using an older version of the code, or an older version of the config file. To test this, you can check the terminal output for training or inference, where the config will be printed at the very beginning. Do you have test_cfg -> multiclass_nms set to False? If so, you are on an older branch.

**Comment by nqxjzm** [comment]
Thanks for your reply very much! I got the latest performence. Amazing work!
|tIoU = 0.30: mAP = 81.72 (%)
|tIoU = 0.40: mAP = 78.05 (%)
|tIoU = 0.50: mAP = 70.87 (%)
|tIoU = 0.60: mAP = 59.42 (%)
|tIoU = 0.70: mAP = 43.73 (%)
Avearge mAP: 66.76 (%)
All done! Total time: 31.43 sec
