### ISSUE TITLE
ActivityNet 1-class vs. 200-class problem

### ISSUE THREAD

**Issue by egoodman92** [happyharrycn/actionformer_release#40]
Hello - thanks for the great contribution. Was wondering, for ActivityNet1.3, is the typical benchmark for the one-class problem? Saw that the config for activitynet config there was "num_classes: 1", and trying to understand if that is standard versus the 200-class problem. (can't seem to find confirmation in other literature) or I am misunderstanding the codebase.

Thanks!!

**Comment by tzzcl** [comment]
Thank you for your interest in our project. 

You are right. In ActionFormer, we directly predict proposals for ActivityNet v1.3 and fuse the proposal with the external classification scores. If we directly learn with the 200-class problem, we will face an extreme imbalance learning problem. 
Many existing works also tries to learn proposals for ActivityNet v1.3 like [G-TAD](https://github.com/frostinassiky/gtad)

**Comment by tzzcl** [comment]
Closed due to inactivity.
