### ISSUE TITLE
in label_points_single_video, why do u select min_len index to build regression target?

### ISSUE THREAD

**Issue by freeman-1995** [happyharrycn/actionformer_release#42]

**Comment by tzzcl** [comment]
In ActionFormer, we build a class-agnostic regression head (for onset/offset regression). 

Please refer to the [PtTransformerRegHead](https://github.com/happyharrycn/actionformer_release/blob/main/libs/modeling/meta_archs.py#L94) Then, we need to reduce the class-aware regression targets to class-agnostic regression targets, then we just choose the minimum one.

**Comment by tzzcl** [comment]
Closed due to inactivity.
