### ISSUE TITLE
Computing mPA

### ISSUE THREAD

**Issue by fsardari** [happyharrycn/actionformer_release#46]
Hi,

I was wondering if you could explian that why you compute the mPA only for 200 first frames of the test video?
Do not we need to compute it for all frames of all test videos?

Thanks

**Comment by tzzcl** [comment]
Hi,

I cannot understand your questions here. For mAP calculation, we use all videos in the test set to compute the mAP. not the first 200 videos/frames.

**Comment by tzzcl** [comment]
Closed due to inactivity
