### ISSUE TITLE
Figure 3. Visualization of our results.

### ISSUE THREAD

**Issue by jiaxibei323** [happyharrycn/actionformer_release#52]
Hello, how is the "Figure 3. Visualization of our results." part of the paper implemented? Is there any visualization code.Thank you.
![image](https://user-images.githubusercontent.com/70988130/191398748-b16b91c3-68f7-45fa-838a-867b47bed712.png)

**Comment by tzzcl** [comment]
We haven't release the visualization code. If you want to implement by yourself, please refer to #13.

**Comment by happyharrycn** [comment]
Closed due to inactivity.

**Comment by Gi-gigi** [comment]
Hi friend, have you implemented visual code by yourself? Can I talk to you? The author still does not provide the code
