### ISSUE TITLE
ActivityNet trainning json file

### ISSUE THREAD

**Issue by houzhijian** [happyharrycn/actionformer_release#57]
Dear authors,

         I have a quick question about the ActivityNet training JSON file. 

         Your released file "anet1.3_tsp_filtered.json" contains the annotation of 9987 videos out of the total 10024 training videos. I wonder why the annotations of the missing videos are filtered. How will the performance be impacted if further adding those missing training samples?

        Thanks for your reply.

**Comment by tzzcl** [comment]
Hi, we are not intended to miss these videos. The ActivityNet dataset only releases the Youtube URL for the video. Thus some videos will become unavailable on Youtube. Increasing the number of training videos will somehow impact the performance, but I think the impact is minor since we only miss around 1% videos.

**Comment by houzhijian** [comment]
Hi, Chen-Lin Zhang,

      Thanks for your quick response! : )

      I still have a further issue. I think the invalid Youtube URL should not be a problem because the current framework is based on offline features.

      Your released data may already contain the TSP features for the full video because the total feature file number is 14950 (10024 training + 4926 validation = 14950).   

     Because of the above statistic, I am puzzled about the reason why the annotations of the missing videos are filtered.

     Looking forward to your reply ; )

**Comment by happyharrycn** [comment]
These videos are filtered if (1) they don’t have TSP features or the number of TSP features don’t match the video duration; or (2) they don’t have any actions that last longer than 0.01 seconds.

**Comment by houzhijian** [comment]
Thanks for the clarity.
