### ISSUE TITLE
Plan to release Ego4d trained model

### ISSUE THREAD

**Issue by HYUNJS** [happyharrycn/actionformer_release#58]
Hello, Dr. Li,

Thank you for sharing your great work. I have seen ActionFormer on the leaderboard of the ego4d moment query benchmark. May I ask that is there any plan to share the result and release the model checkpoint trained on ego4d?

**Comment by happyharrycn** [comment]
The Ego4D team has requested us to post our solution by Nov 18th. We will follow that date for releasing the pre-trained models.
