### ISSUE TITLE
How to reproduce results using i3d for ActivityNet?

### ISSUE THREAD

**Issue by g1910** [happyharrycn/actionformer_release#59]
Dear authors,

First of all, great work with ActionFormer. I wish to reproduce results on ActivityNet using i3d features. Could you please make available the features and the config file that I can use to train the model? 

Thanks in advance

**Comment by happyharrycn** [comment]
We can work on this, yet probably with a lower priority. Those I3D features are much larger (in storage) than the TSP features, and produce slightly worse results.

**Comment by g1910** [comment]
Thanks for a prompt response @happyharrycn. Are these I3D features the standard ones used by other repos or are they something that you specifically pre-process for actionformer? Is there a way you can prioritize making them available? If storage is an issue, I can provide a link to you to make them available as I have generous amount of storage on my end. Thanks!

**Comment by tzzcl** [comment]
Hi, for ActivityNet I3D features, we use the feature provided by [CMCS](https://github.com/Finspire13/CMCS-Temporal-Action-Localization). You can still download the original feature from [CMCS link](https://pan.baidu.com/s/1KJxNE-_We-9AcBs0N6xTXA#list/path=%2F). But it will need a BaiduYun VIP account and around 500G disk. After downloading the feature, you can find the I3D feature in it.

**Comment by g1910** [comment]
Thanks @tzzcl for providing the features. Can you also provide the config file that I can use for i3d features? And also provide guidance on any other change I might need to do in the code to run with i3d features?

**Comment by happyharrycn** [comment]
As far as I recall, we downsampled the features and uses a config file similar to our TSP features. I can dig into our internal repo and find the config file this weekend.

**Comment by AwalkZY** [comment]
Also looking forward to the I3D-based configuration and related code files. Thanks a lot!

**Comment by happyharrycn** [comment]
This should now been addressed by commit bc9c4c62d9471b711cefcfd3fc8e8da3e5e89cb5 (config file) and 88f6110a25d43f92ee9c4fb193eea8564296590e (documentation). 

Let us know if there is any further issue.

**Comment by happyharrycn** [comment]
@g1910 @AwalkZY I will mark this as resolved (see the latest commits) unless further issues are raised.
