### ISSUE TITLE
Question about such strong I3D feature

### ISSUE THREAD

**Issue by yangmin666** [happyharrycn/actionformer_release#60]
I3D feature you provided is much stronger than public I3D feature(eg:tadtr,rtd-net use them). Also, I3D feature you provided is 4x downsampled while public feature is 8x downsampled. How did you generate this feature? Another question, do you have a result of I3D without flow branch?  Thanks!

**Comment by tzzcl** [comment]
for the feature extraction part, you can refer to the original [CMCS](https://github.com/Finspire13/CMCS-Temporal-Action-Localization) repo for more details. For RGB-only results, you can just reduce the feature channel to 1024 (we directly concatenate the RGB/Flow features) and re-run the experiments.

**Comment by happyharrycn** [comment]
I am not totally sure what you referred to as stronger I3D features. The features are extracted from the same I3D pre-trained on Kinetics, also used by previous works (e.g., CMCS). Yes, the feature is extracted every 4 frames, as we described in the paper. If one take the features by every 8 frames, the performance of our model is roughly the same (see our ablation in Table C Appendix).

Like Chenlin had mentioned, taking the first half of the feature channels will give you the RGB features.

**Comment by happyharrycn** [comment]
Closed due to inactivity. Let us know if you have further questions.

**Comment by csrhddlam** [comment]
> for the feature extraction part, you can refer to the original [CMCS](https://github.com/Finspire13/CMCS-Temporal-Action-Localization) repo for more details. For RGB-only results, you can just reduce the feature channel to 1024 (we directly concatenate the RGB/Flow features) and re-run the experiments.

According to the suggestion, I tried only using the first N channels in the i3d features provided on THUMOS, and run exactly the command provided. Here is the mAP I got:
first 512 channels, 55.1; 
first 1024 channels (i.e. RGB only), 51.7; 
first 1536 channels, 64.2; 
first 2048 channels (all of the channels), 66.5.

Does it make sense? The last 1024 dimensions (i.e. flow features) seem to contribute A LOT.

**Comment by happyharrycn** [comment]
We did not explore using RGB features along on THUMOS14, and I won't comment on these numbers. There is an caveat though. When feature channels are reduced, the model size (e.g., embedding / FPN / head dims) often has to be shrunk accordingly (see our config in anet_tsp.yaml). 

I would suggest the setting of taking the first 1024 channels (RGB features), and reducing the model size by half (setting embedding / FPN / head dims to 256). Hyperparameter for train might need to be tweaked if overfitting / underfitting is observed.

**Comment by tzzcl** [comment]
In addition to Yin's answers, I've verfied that the first 1024 channels are the RGB feature and the remaining 1024 channels are the flow feature (average of the original 10-crop features).

**Comment by Go2Heart** [comment]
> > for the feature extraction part, you can refer to the original [CMCS](https://github.com/Finspire13/CMCS-Temporal-Action-Localization) repo for more details. For RGB-only results, you can just reduce the feature channel to 1024 (we directly concatenate the RGB/Flow features) and re-run the experiments.
> 
> According to the suggestion, I tried only using the first N channels in the i3d features provided on THUMOS, and run exactly the command provided. Here is the mAP I got: first 512 channels, 55.1; first 1024 channels (i.e. RGB only), 51.7; first 1536 channels, 64.2; first 2048 channels (all of the channels), 66.5.
> 
> Does it make sense? The last 1024 dimensions (i.e. flow features) seem to contribute A LOT.

Hello, I have been recently working on your similar settings (i.e. input I3D rgb feature only). I only keep the provided I3D feature in [T, :1024], which results in [T, 1024]. But I have failed to reproduce your result of 51.7 mAP. The result in my experiment is only 23.9. I wonder which part could be different to produce these 2 different results, since the only change in training and evaluation code should the `input_dim` in thumos.yaml only.

**Comment by tjvvai** [comment]
I also have the similar score around 25 average ap if I only use the first 1024 (e.g. rgb features)
