### ISSUE TITLE
Why are the reported results of TadTR on Thumos14 and ActivityNet quite different with those in TadTR paper?

### ISSUE THREAD

**Issue by Gttgithub** [happyharrycn/actionformer_release#62]
Thank you for your good job!
I found that the results are very different between your paper and TadTR paper on Thumos14 and ActivityNet datasets? 
Are there some specific implementation details?

![bcac8b0e67166b446d72a53b9516ca4](https://user-images.githubusercontent.com/74762830/197515606-51724ca8-cbfb-4b64-9cf2-8bf830a40995.png)
![ac8282c74c2b5aad330719c2e9e2c96](https://user-images.githubusercontent.com/74762830/197515624-f9df057e-65d6-4309-8fb5-8b7d6acd95b8.png)

**Comment by happyharrycn** [comment]
These results are from the arXiv version of TadTR during the submission of the paper. This older version can be accessed from [this link on arXiv](https://arxiv.org/pdf/2106.10271v2.pdf). TadTR has subsequently updated the results (with the latest arXiv version this Aug). We are happy to incorporate their latest results in our arXiv version (probably after all conference deadlines this fall).

**Comment by happyharrycn** [comment]
I will mark this closed for now unless further questions arise.
