### ISSUE TITLE
about win_size

### ISSUE THREAD

**Issue by nqxjzm** [happyharrycn/actionformer_release#63]
Sorry to bother you, I think the win_size of different Fpn-LEVEL should be different. But in actionformer, you use the same 19 for thumos14, so I want to ask  whether it's use win_size such as[64, 32 ,16, 8, 4, 2] in FPN_feature level?

**Comment by tzzcl** [comment]
I don't fully understand your question here. For window size, we keep the win_size of each fpn-level as same (19) on THUMOS14. Thus the feature points in  first layer will have 19 receptive field, and the feature points in second layer will have 19*2=38, and so on.
In your case, [64, 32, 16, 8, 4, 2] means all feature point in different FPN level will have the same receptive field. The feature points in the first layer will have 64 receptive field, the feature points in the second layer will have 32*2=64 receptive field, which is problematic here.

**Comment by nqxjzm** [comment]
I get it , I misunderstand your code in some way..
