### ISSUE TITLE
What is the test video number of Thumos14 dataset?

### ISSUE THREAD

**Issue by fake-warrior8** [happyharrycn/actionformer_release#65]
Hi, I found that the test set included only 212 videos and 3358 clips in the thumos14.json. However, it is 213 videos in your paper. Is there something wrong? 

The video id list is ['video_test_0000004', 'video_test_0000006', 'video_test_0000007', 'video_test_0000011', 'video_test_0000026', 'video_test_0000028', 'video_test_0000039', 'video_test_0000045', 'video_test_0000046', 'video_test_0000051', 'video_test_0000058', 'video_test_0000062', 'video_test_0000073', 'video_test_0000085', 'video_test_0000113', 'video_test_0000129', 'video_test_0000131', 'video_test_0000173', 'video_test_0000179', 'video_test_0000188', 'video_test_0000211', 'video_test_0000220', 'video_test_0000238', 'video_test_0000242', 'video_test_0000250', 'video_test_0000254', 'video_test_0000270', 'video_test_0000273', 'video_test_0000278', 'video_test_0000285', 'video_test_0000292', 'video_test_0000293', 'video_test_0000308', 'video_test_0000319', 'video_test_0000324', 'video_test_0000353', 'video_test_0000355', 'video_test_0000357', 'video_test_0000367', 'video_test_0000372', 'video_test_0000374', 'video_test_0000379', 'video_test_0000392', 'video_test_0000405', 'video_test_0000412', 'video_test_0000413', 'video_test_0000423', 'video_test_0000426', 'video_test_0000429', 'video_test_0000437', 'video_test_0000442', 'video_test_0000443', 'video_test_0000444', 'video_test_0000448', 'video_test_0000450', 'video_test_0000461', 'video_test_0000464', 'video_test_0000504', 'video_test_0000505', 'video_test_0000538', 'video_test_0000541', 'video_test_0000549', 'video_test_0000556', 'video_test_0000558', 'video_test_0000560', 'video_test_0000569', 'video_test_0000577', 'video_test_0000591', 'video_test_0000593', 'video_test_0000601', 'video_test_0000602', 'video_test_0000611', 'video_test_0000615', 'video_test_0000617', 'video_test_0000622', 'video_test_0000624', 'video_test_0000626', 'video_test_0000635', 'video_test_0000664', 'video_test_0000665', 'video_test_0000671', 'video_test_0000672', 'video_test_0000673', 'video_test_0000689', 'video_test_0000691', 'video_test_0000698', 'video_test_0000701', 'video_test_0000714', 'video_test_0000716', 'video_test_0000718', 'video_test_0000723', 'video_test_0000724', 'video_test_0000730', 'video_test_0000737', 'video_test_0000740', 'video_test_0000756', 'video_test_0000762', 'video_test_0000765', 'video_test_0000767', 'video_test_0000771', 'video_test_0000785', 'video_test_0000786', 'video_test_0000793', 'video_test_0000796', 'video_test_0000798', 'video_test_0000807', 'video_test_0000814', 'video_test_0000839', 'video_test_0000844', 'video_test_0000846', 'video_test_0000847', 'video_test_0000854', 'video_test_0000864', 'video_test_0000873', 'video_test_0000882', 'video_test_0000887', 'video_test_0000896', 'video_test_0000897', 'video_test_0000903', 'video_test_0000940', 'video_test_0000946', 'video_test_0000950', 'video_test_0000964', 'video_test_0000981', 'video_test_0000987', 'video_test_0000989', 'video_test_0000991', 'video_test_0001008', 'video_test_0001038', 'video_test_0001039', 'video_test_0001040', 'video_test_0001058', 'video_test_0001064', 'video_test_0001066', 'video_test_0001072', 'video_test_0001075', 'video_test_0001076', 'video_test_0001078', 'video_test_0001079', 'video_test_0001080', 'video_test_0001081', 'video_test_0001098', 'video_test_0001114', 'video_test_0001118', 'video_test_0001123', 'video_test_0001127', 'video_test_0001129', 'video_test_0001134', 'video_test_0001135', 'video_test_0001146', 'video_test_0001153', 'video_test_0001159', 'video_test_0001162', 'video_test_0001163', 'video_test_0001164', 'video_test_0001168', 'video_test_0001174', 'video_test_0001182', 'video_test_0001194', 'video_test_0001195', 'video_test_0001201', 'video_test_0001202', 'video_test_0001207', 'video_test_0001209', 'video_test_0001219', 'video_test_0001223', 'video_test_0001229', 'video_test_0001235', 'video_test_0001247', 'video_test_0001255', 'video_test_0001257', 'video_test_0001267', 'video_test_0001268', 'video_test_0001270', 'video_test_0001276', 'video_test_0001281', 'video_test_0001307', 'video_test_0001309', 'video_test_0001313', 'video_test_0001314', 'video_test_0001319', 'video_test_0001324', 'video_test_0001325', 'video_test_0001339', 'video_test_0001343', 'video_test_0001358', 'video_test_0001369', 'video_test_0001389', 'video_test_0001391', 'video_test_0001409', 'video_test_0001431', 'video_test_0001433', 'video_test_0001446', 'video_test_0001447', 'video_test_0001452', 'video_test_0001459', 'video_test_0001460', 'video_test_0001463', 'video_test_0001468', 'video_test_0001483', 'video_test_0001484', 'video_test_0001495', 'video_test_0001496', 'video_test_0001508', 'video_test_0001512', 'video_test_0001522', 'video_test_0001527', 'video_test_0001531', 'video_test_0001532', 'video_test_0001549', 'video_test_0001556', 'video_test_0001558'].

**Comment by tzzcl** [comment]
Hi, we exclude the video "1292" from the THUMOS14 test dataset, because it doesn't have any ground truth action annotation.
