### ISSUE TITLE
Visualization code

### ISSUE THREAD

**Issue by minghu0830** [happyharrycn/actionformer_release#66]
Excellent work! We have reproduced your code on our own dataset. I wonder if you can share the Visualization code in the paper with me. Thank you very much!

![20221104151558](https://user-images.githubusercontent.com/113792384/199915439-d55f782b-2726-485b-9aa8-2edbf8bb1a17.png)

**Comment by minghu0830** [comment]
my email:ming.hu@monash.edu

**Comment by tzzcl** [comment]
Hi, we haven't released the visualization code since it is somewhat complex and needs some manual steps. If you need to re-implement the visualization part, please refer to #13.

**Comment by tzzcl** [comment]
Closed due to inactivity, if you have further question, just send me emails.
