### ISSUE TITLE
why set num_classes as 1 in ActivityNet dataset module?

### ISSUE THREAD

**Issue by fake-warrior8** [happyharrycn/actionformer_release#67]
Hi, I want to know why you set num_classes as 1 in ActivityNet dataset module [line122](https://github.com/happyharrycn/actionformer_release/blob/ac6ff26adb7ec64904bf52b4b222000f7dfc45f5/libs/datasets/anet.py#L122), which make the gold label is a trivial zero. The setting comes from anet_tsp.yaml.

dataset: {
  json_file: ./data/anet_1.3/annotations/anet1.3_tsp_filtered.json,
  feat_folder: ./data/anet_1.3/tsp_features,
  file_prefix: v_,
  file_ext: .npy,
  **num_classes: 1,**
  input_dim: 512,
  feat_stride: 16,
  num_frames: 16,
  default_fps: 15,
  trunc_thresh: 0.5,
  crop_ratio: [0.9, 1.0],
  # upsample the features to a fixed length of 192
  max_seq_len: 192,
  force_upsampling: True,
}

**Comment by tzzcl** [comment]
For ActivityNet v1.3, we learn action proposals rather than the real action instances due to the optimization issue. We comine the action proposals with external action classifiers to obtain the final action predictions, if you have more question, please refer to our draft.

**Comment by fake-warrior8** [comment]
> For ActivityNet v1.3, we learn action proposals rather than the real action instances due to the optimization issue. We comine the action proposals with external action classifiers to obtain the final action predictions, if you have more question, please refer to our paper .

I will check it. Thank you!
