### ISSUE TITLE
EPIC Kitchens action？

### ISSUE THREAD

**Issue by wolfworld6** [happyharrycn/actionformer_release#7]
Have you trained models for action on EPIC Kitchens？

**Comment by happyharrycn** [comment]
In the EPIC-Kitchens dataset, each "action" is defined as a combination of a verb and a noun. In theory, one can take the models for recognizing nouns / verbs from this repo, and merge their results for localizing "actions" on EPIC-Kitchens. We have not explored this route thoroughly and might work on that later.

**Comment by wolfworld6** [comment]
> In the EPIC-Kitchens dataset, each "action" is defined as a combination of a verb and a noun. In theory, one can take the models for recognizing nouns / verbs from this repo, and merge their results for localizing "actions" on EPIC-Kitchens. We did have initial results for doing so, yet have not explored this route thoroughly. We will work on that later.

thx，could you show me your extract script for the features？

**Comment by happyharrycn** [comment]
If you are referring to video feature extraction, we used a modified version of the [SlowFast repo](https://github.com/facebookresearch/SlowFast). We don't have a concrete plan for releasing the feature extraction code, but can work on upon requests.

**Comment by wolfworld6** [comment]
> 

thx，vvvvvvvery much！
