### ISSUE TITLE
About extracting feature.

### ISSUE THREAD

**Issue by EdenGabriel** [happyharrycn/actionformer_release#70]
Hi,
Thank you for your excellent work. I have a qusetion about extracting features for epic-kitchens100.
In the link your provided, it corresponds to a vector of 2304 dim for about 0.533s in a video. I want to know some details about features extracted. i.e. if 2304=16*12*12, that means T=16,H=W=12 for per frame? (AHa, this is just my personal guess. )
What if I want to get ROIPooling feature per frame, may i get some advice from you?
Looking forward to your reply. Thank you.

**Comment by tzzcl** [comment]
For your questions, we use a typical SlowFast network on EPIC-Kitchens. Thus the input clip is 32*256*256, after the SlowFast network (with 3D global average pooling), it will become a 2304d feature, and this is the feature we used for EPIC-Kitchens. Thus we don't apply any ROIPooling features. For more details, please refer to the [SlowFast paper](https://arxiv.org/abs/1812.03982) and [SlowFast code](https://github.com/facebookresearch/SlowFast/blob/main/slowfast/models/video_model_builder.py#L173)

**Comment by happyharrycn** [comment]
Marked as closed. Feel free to re-open this issue if further questions arise.
