### ISSUE TITLE
Question about regression ranges

### ISSUE THREAD

**Issue by zivnachum** [happyharrycn/actionformer_release#71]
Hi, I have a dataset with actions that are much longer than the action in THUMOS.
I'm trying to understand how to choose regression ranges that will fit my data best.
Any suggestions on how to do it and how to interpret their values? Thanks!

**Comment by zivnachum** [comment]
Thanks for the response!
I have another couple of follow-up questions.
1. If regression range means the maximum regression time from the current timestamp to the start/end of the action, does it mean the duration of an event?
2. What do you mean by increasing the number of multi-level features? Adding more levels to the pyramid? 
3. Comparing Ego4D config with THUMOS config, the regression ranges overlap. Is there a specific reason to do so?

Thanks again!

**Comment by happyharrycn** [comment]
To add to Chen-Lin's comments, if you are looking for localizing actions of much longer duration, possible strategies include

- Use a larger temporal stride to extract video features. A high temporal resolution for video features will not be necessary for detecting long actions, and might introduce label imbalance problems, leading to potential performance degradation. 
- Increase the regression range on all feature pyramid levels. This will increase the duration of "template" events, as described in Chen-Lin's comments. For example, you can try to double the regression range. 
- Increase the number of pyramid levels. This will allow the model to adapt to a larger variation of the action durations.

**Comment by zivnachum** [comment]
Thanks! Much appreciated!
