### ISSUE TITLE
import nms_1d_cpu ImportError

### ISSUE THREAD

**Issue by JiangZhouHao** [happyharrycn/actionformer_release#72]
Thank you for your excellent work firstly. 
When I import nms_1d_cpu, ImportError: .local/lib/python3.7/site-packages/nms_1d_cpu-0.0.0-py3.7-linux-x86_64.egg/nms_1d_cpu.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor6deviceEv

**Comment by tzzcl** [comment]
Can you tell me your PyTorch version, I think you may have a different PyTorch rather than recommended (PyTorch 1.11.0).

**Comment by JiangZhouHao** [comment]
> Can you tell me your PyTorch version, I think you may have a different PyTorch rather than recommended (PyTorch 1.11.0).
Thank you for your quick reply.
The version 
torch 1.11.0
numpy 1.17.0
CUDA 11.0
Firstly, I thought maybe it's because of different Pytorch, so I had changed my torch version from 1.13.1 to 1.11.0, but it still didn't work.

**Comment by tzzcl** [comment]
as far as I know, I don't think you correctly installed PyTorch. You may installed the CPU version of PyTorch, thus it failed. PyTorch 1.11.0 will support CUDA 11.1/11.3, but not CUDA 11.0.

**Comment by JiangZhouHao** [comment]
> as far as I know, I don't think you correctly installed PyTorch. You may installed the CPU version of PyTorch, thus it failed. PyTorch 1.11.0 will support CUDA 11.1/11.3, but not CUDA 11.0.
Thank you, I will try it again. Thanks for your brilliant work, NB!!!
