### ISSUE TITLE
Measure GMACs/FLOPS

### ISSUE THREAD

**Issue by TuanTNG** [happyharrycn/actionformer_release#75]
Thank you for your awesome work. 
Would you mind sharing how did you measure the GMACs as reported in table 3c? 
Thank you in advance.

**Comment by tzzcl** [comment]
Hi, since it doesn't have a convenient way to calculate the FLOPs of our model like [flops-counter](https://github.com/sovrasov/flops-counter.pytorch). We manually added a flops method to calculate FLOPs for each block in our network in a top-down manner.

**Comment by TuanTNG** [comment]
Thank you for your response. I got it
