### ISSUE TITLE
Training without gt_segments, gt_labels.

### ISSUE THREAD

**Issue by grayfactory** [happyharrycn/actionformer_release#78]
Hi, thanks for great work! 
I have question about to training model on dataset which without segment and label informations.

I expected that if the model could be trained by the THUMOS14 dataset, it would be equally possible to train with without annotations. but I found in meta_archs.py

```
 assert video_list[0]['segments'] is not None, "GT action labels does not exist"
 assert video_list[0]['labels'] is not None, "GT action labels does not exist"
```

Is it possible to train with data without label and segment information?
Looking forward to your reply. Thank you.

**Comment by happyharrycn** [comment]
This is not possible. Our model assumes a fully supervised setting, where action annotations (labels and onsets/offsets) are provided during training. Indeed, our work and prior works considers a subset of THUMOS14 dataset with temporal annotations. More details regarding the datasets and training schemes can be found in the paper.

**Comment by grayfactory** [comment]
Thank you for your quick reply. I get the point!
