### ISSUE TITLE
Hello, the author, I don't know whether your experiment has the result of recall rate or AR@AN

### ISSUE THREAD

**Issue by jiaxibei323** [happyharrycn/actionformer_release#80]
Hello, the author, I don't know whether your experiment has the result of recall rate or AR@AN

**Comment by tzzcl** [comment]
Actionformer is an one-stage action detector, we don't have recall rate/ AR@AN like those action proposal methods.

**Comment by happyharrycn** [comment]
To add to Chen-Lin's comment, AR@AN is often used to evaluate action proposals, which are not used by our model. The repo does include code for recall at top-K (see [here](https://github.com/happyharrycn/actionformer_release/blob/e559d1c4ba85ba24650067c6f6a9db605ae3ecb8/libs/utils/metrics.py#L336)). Feel free to adapt the code if you want to evaluate AR@AN.

**Comment by jiaxibei323** [comment]
Thank you very much for your reply. I will try to do it.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "happyharrycn/actionformer_release"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月29日(星期天) 上午7:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [happyharrycn/actionformer_release] Hello, the author, I don't know whether your experiment has the result of recall rate or ***@***.*** (Issue #80)





 
To add to Chen-Lin's comment, ***@***.*** is often used to evaluate action proposals, which are not used by our model. The repo does include code for recall at top-K (see here). Feel free to adapt the code if you want to evaluate ***@***.***
