### ISSUE TITLE
不连续时间帧的回归问题

### ISSUE THREAD

**Issue by tingfengwanxiao** [happyharrycn/actionformer_release#85]
您好，如果我在使用自己的数据集，但是它并不是稳定的帧率，比如1-2帧的时间间隔是30ms，2-3帧的时间间隔是50ms，这样的话还能使用这个模型回归准确的时间位置吗？是不是预测哪一帧最后手动换算成时间更好一点？或者作者有什么简单的建议吗？

**Comment by tzzcl** [comment]
对于你的问题，我觉得，可能基于逐帧的分类任务更好一点，不稳定帧率对于计算时间偏移来说，是比较固定的。

**Comment by tingfengwanxiao** [comment]
好的好的

**Comment by happyharrycn** [comment]
Mark as closed.
