### ISSUE TITLE
nms_1d_cpu

### ISSUE THREAD

**Issue by persona97** [happyharrycn/actionformer_release#9]
Hi, It seems that the ./libs/utils/nms.py import module name 'nms_1d_cpu' 
Where could I find this module? It seems that nms.py is from mmcv but I cannot find any nms_1d_cpu named file in mmcv github...

**Comment by tzzcl** [comment]
The code is in [nms_cpu.cpp](https://github.com/happyharrycn/actionformer_release/blob/main/libs/utils/csrc/nms_cpu.cpp).

You may need to refer to the Compile section in [INSTALL.md](https://github.com/happyharrycn/actionformer_release/blob/main/INSTALL.md) for details.

**Comment by persona97** [comment]
Oh, I have missed that part. Thank you for the fast comment
