### ISSUE TITLE
Why replace the predicted labels?

### ISSUE THREAD

**Issue by bhosalems** [happyharrycn/actionformer_release#95]
Why do we have the below replacement in the evaluate.py?
 # make the label ids consistent
        preds['label'] = preds['label'].replace(self.activity_index) 

What happens if the validation or the test dataset does not have all the possible labels?

**Comment by tzzcl** [comment]
We follow the original ActivityNet evaluation code to replace the original string with the index to eval predictions. For your case, I think you should manually build the activity_index with the union of your all data.

**Comment by bhosalems** [comment]
thanks for the reply.
