### ISSUE TITLE
Guidelines on setting up config for custom datasets?

### ISSUE THREAD

**Issue by bhosalems** [happyharrycn/actionformer_release#99]
Hi,
I am using action former as a baseline in one of our works, I want to setup the config for our dataset. Is there any guide on how to set the parameters in the config, for now, I have populated almost all the fields from the THUMOS config file.

**Comment by tzzcl** [comment]
For most custom datasets, I think hyperparameters from THUMOS14 is OK, and you just need to change the stride, feature dimension, etc.

**Comment by bhosalems** [comment]
Okay, what's the number of frames?

**Comment by tzzcl** [comment]
num_frames means each clip uses `num_frames` of input frames to generate that figure, for example, I3D uses 16 frames to generate one feature vector.

**Comment by bhosalems** [comment]
I don't understand what parameter that would be from the I3D extraction script, I have little knowledge of the I3D feature extraction method recommended by you here https://github.com/Finspire13/pytorch-i3d-feature-extraction?

These are the parameters -
--mode:              rgb or flow
--load_model:        path of the I3D model
--input_dir:         folder of converted videos
--output_dir:        folder of extracted features
--batch_size:        batch size for snippets
--sample_mode:       oversample, center_crop or resize
--frequency:         how many frames between adjacent snippet
--usezip/no-usezip:  whether the frame images are zipped

**Comment by happyharrycn** [comment]
We have limited capacity and can only address question directly related to this repo. For I3D, please refer to their paper and the repo for more details.
